name: Deploy to Target Org

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Salesforce CLI
        run: npm install --global @salesforce/cli

      - name: Authenticate to Target Org
        run: echo "${{ secrets.SF_AUTH_URL }}" > auth.txt && sf org login sfdx-url --sfdx-url-file auth.txt -a TargetOrg

      - name: Deploy metadata
        run: sf project deploy start --manifest salesforce-deployment/manifest/package.xml --target-org TargetOrg
